import re

with open('D:/Reps/PETS/assets/_piano_html.txt', encoding='utf-8') as f:
    piano_html = f.read()

with open('D:/Reps/PETS/guitar_template.html', encoding='utf-8') as f:
    guitar_html = f.read()

note_sel = re.search(r'<select[^>]*id="note"[^>]*>.*?</select>', guitar_html, re.DOTALL).group(0)
scale_sel = re.search(r'<select[^>]*id="scale"[^>]*>.*?</select>', guitar_html, re.DOTALL).group(0)

html = (
'<!DOCTYPE html>\n'
'<html lang="en">\n'
'<head>\n'
'<meta charset="UTF-8">\n'
'<meta name="viewport" content="width=device-width">\n'
'<title>Chord.Rocks - Offline</title>\n'
'<link rel="stylesheet" href="assets/styles.min.css">\n'
'<link rel="stylesheet" href="assets/instrument_stringed.min.css">\n'
'<link rel="stylesheet" href="assets/instrument_options.min.css">\n'
'<link rel="stylesheet" href="assets/scales_info.min.css">\n'
'<link id="instrument_css" rel="stylesheet" href="assets/instrument_guitar.min.css">\n'
'<style>\n'
'#app_bar{background:#2c3e50;padding:8px 16px;display:flex;align-items:center;gap:12px;flex-wrap:wrap}\n'
'#app_bar label{color:#aaa;font-size:13px;white-space:nowrap}\n'
'#app_instrument_select{padding:5px 10px;font-size:14px;border-radius:4px;border:none;background:#ecf0f1}\n'
'#piano_section{display:none}\n'
'.hidden{display:none}\n'
'</style>\n'
'</head>\n'
'<body>\n'
'\n'
'<div id="app_bar">\n'
'  <img src="assets/chords-logo.png" alt="Chord.Rocks" height="32">\n'
'  <label for="app_instrument_select">Instrument:</label>\n'
'  <select id="app_instrument_select">\n'
'    <option value="guitar">Guitar</option>\n'
'    <option value="piano">Piano</option>\n'
'    <option value="bass-guitar">Bass Guitar</option>\n'
'    <option value="ukulele">Ukulele</option>\n'
'    <option value="violin-fiddle">Violin / Fiddle</option>\n'
'    <option value="mandolin">Mandolin</option>\n'
'    <option value="5-string-bass-guitar">5 String Bass Guitar</option>\n'
'    <option value="6-string-bass-guitar">6 String Bass Guitar</option>\n'
'    <option value="7-string-guitar">7 String Guitar</option>\n'
'    <option value="8-string-guitar">8 String Guitar</option>\n'
'    <option value="9-string-guitar">9 String Guitar</option>\n'
'    <option value="10-string-guitar">10 String Guitar</option>\n'
'    <option value="baritone-guitar">Baritone Guitar</option>\n'
'    <option value="5-string-violin-fiddle">5 String Violin / Fiddle</option>\n'
'  </select>\n'
'</div>\n'
'\n'
'<div id="page_content_con">\n'
'<form method="get" action="#" onsubmit="return false">\n'
'\n'
'  <div class="info_con" id="option_con">\n'
'    <div>\n'
'      <div class="op" id="tuning_op">\n'
'        <label for="tuning">Tuning</label>\n'
'        <div id="tuning_con"></div>\n'
'      </div>\n'
'      <div class="op">\n'
'        <label for="accidental">Accidental</label>\n'
'        <select name="accidental" id="accidental">\n'
'          <option value="sharp" selected>Sharp</option>\n'
'          <option value="flat">Flat</option>\n'
'        </select>\n'
'      </div>\n'
'    </div>\n'
'    <div>\n'
'      <div class="op">\n'
'        <label for="note">Note</label>\n'
+ note_sel + '\n'
'      </div>\n'
'      <div class="op">\n'
'        <label for="scale">Scale</label>\n'
+ scale_sel + '\n'
'      </div>\n'
'    </div>\n'
'    <div id="stringed_extra_ops">\n'
'      <div class="op">\n'
'        <label for="capo_fret">Capo</label>\n'
'        <select name="capo_fret" id="capo_fret"><option value="0">None</option></select>\n'
'      </div>\n'
'      <div class="op">\n'
'        <label><input type="checkbox" id="lefty"> Left Handed</label>\n'
'      </div>\n'
'    </div>\n'
'  </div>\n'
'\n'
'  <div id="submit_button_con" class="hidden"><button type="submit">Go</button></div>\n'
'  <div id="op_submit_button_con" class="hidden"><button type="submit">Update</button></div>\n'
'\n'
'  <div id="stringed_section"></div>\n'
'\n'
'  <div id="piano_section">\n'
+ piano_html + '\n'
'  </div>\n'
'\n'
'  <div class="info_con" id="info_con">\n'
'    <div id="scale_info_con">\n'
'      <div class="header">Scale Info</div>\n'
'      <h2 id="info_scale_name"></h2>\n'
'      <dl>\n'
'        <dt>notes</dt><dd id="info_scale_notes"></dd>\n'
'        <dt>degrees</dt><dd id="info_scale_degrees"></dd>\n'
'        <dt>steps</dt><dd id="info_scale_steps"></dd>\n'
'        <dt>semitones</dt><dd id="info_scale_semitones"></dd>\n'
'        <dt id="info_scale_name_alt_label">alternative name</dt>\n'
'        <dd id="info_scale_name_alt"></dd>\n'
'      </dl>\n'
'      <div class="header">Chord Info</div>\n'
'      <h2 id="info_chord_name">Select A Chord</h2>\n'
'      <aside id="chord_info" class="hidden">\n'
'        <dl>\n'
'          <dt>notes</dt><dd id="info_chord_notes"></dd>\n'
'          <dt>degrees</dt><dd id="info_chord_degrees"></dd>\n'
'          <dt>abbreviation</dt><dd id="info_chord_abbrev"></dd>\n'
'          <dt id="info_chord_name_alt_label" class="hidden">alternative name</dt>\n'
'          <dd id="info_chord_name_alt" class="hidden"></dd>\n'
'        </dl>\n'
'      </aside>\n'
'    </div>\n'
'    <div id="directions_con"></div>\n'
'    <div id="chord_list_con">\n'
'      <table id="scale_chord_table">\n'
'        <thead><tr class="scale_chord_tr"></tr></thead>\n'
'        <tbody></tbody>\n'
'      </table>\n'
'    </div>\n'
'  </div>\n'
'\n'
'</form>\n'
'</div>\n'
'\n'
'<script src="assets/jquery.min.js"></script>\n'
'<script src="assets/all_instruments.js"></script>\n'
'<script src="assets/note.class.min.js"></script>\n'
'<script src="assets/chords.data.min.js"></script>\n'
'<script src="assets/scales.data.min.js"></script>\n'
'<script src="assets/chord.class.min.js"></script>\n'
'<script src="assets/scale.class.min.js"></script>\n'
'<script src="assets/pageMeta.class.min.js"></script>\n'
'<script src="assets/instrumentOptions.class.min.js"></script>\n'
'<script src="assets/scalesPage.min.js"></script>\n'
'<script src="assets/scalesStringed.class.min.js"></script>\n'
'<script src="assets/keyPositionPiano.class.min.js"></script>\n'
'\n'
'<script>\n'
'var NOTE_VALUES = ["a","a-sharp","b","c","c-sharp","d","d-sharp","e","f","f-sharp","g","g-sharp"];\n'
'\n'
'var instrumentMeta = {\n'
'  "guitar":                 {css:"instrument_guitar"},\n'
'  "bass-guitar":            {css:"instrument_bass-guitar"},\n'
'  "ukulele":                {css:"instrument_ukulele"},\n'
'  "violin-fiddle":          {css:"instrument_violin-fiddle"},\n'
'  "mandolin":               {css:"instrument_mandolin"},\n'
'  "5-string-bass-guitar":   {css:"instrument_5-string-bass-guitar"},\n'
'  "6-string-bass-guitar":   {css:"instrument_6-string-bass-guitar"},\n'
'  "7-string-guitar":        {css:"instrument_7-string-guitar"},\n'
'  "8-string-guitar":        {css:"instrument_8-string-guitar"},\n'
'  "9-string-guitar":        {css:"instrument_9-string-guitar"},\n'
'  "10-string-guitar":       {css:"instrument_10-string-guitar"},\n'
'  "baritone-guitar":        {css:"instrument_baritone-guitar"},\n'
'  "5-string-violin-fiddle": {css:"instrument_5-string-violin-fiddle"},\n'
'  "piano":                  {css:"instrument_piano"}\n'
'};\n'
'\n'
'function generateFretboard(info) {\n'
'  var ns = info.notes.length, nf = info.num_frets_desktop;\n'
'  var dots = [3,5,7,9,15,17,19,21], dbl = [12,24];\n'
'  var h = "<div id=\'stringed_display\'><div id=\'fret_marker_con\'><div id=\'string_label_con\'>";\n'
'  for (var s = ns-1; s >= 0; s--) {\n'
'    var nk = info.notes[s] % 12;\n'
'    h += "<div id=\'string_label_"+s+"\' class=\'string_label\' data-note=\'"+nk+"\'>"+Note.getNote(nk)+"</div>";\n'
'  }\n'
'  h += "</div>";\n'
'  for (var f = 0; f <= nf; f++) {\n'
'    var fc = "fret_con"+(f>=11?" hidden_tablet":f>=7?" hidden_mobile":"");\n'
'    h += "<div class=\'"+fc+"\' id=\'fret_"+f+"\'><div class=\'fret_label\'>"+f+"</div><div class=\'fret\'>";\n'
'    if (dbl.indexOf(f)>=0) h += "<div class=\'fret_dot dot_b\'></div><div class=\'fret_dot dot_t\'></div>";\n'
'    else if (dots.indexOf(f)>=0) h += "<div class=\'fret_dot\'></div>";\n'
'    h += "</div></div>";\n'
'  }\n'
'  h += "</div><div id=\'fret_note_con\'>";\n'
'  for (var f = 0; f <= nf; f++) {\n'
'    var nc = "note_con"+(f>=11?" hidden_tablet":f>=7?" hidden_mobile":"");\n'
'    h += "<div id=\'f_"+f+"\' class=\'"+nc+"\'>";\n'
'    if (f===0) {\n'
'      h += "<div id=\'capo_con\'><div class=\'capo\'></div></div><div id=\'string_x_con\'>";\n'
'      for (var s = ns-1; s >= 0; s--) h += "<div id=\'s_x_"+s+"\' class=\'sf\'><span>X</span></div>";\n'
'      h += "</div>";\n'
'    }\n'
'    for (var s = ns-1; s >= 0; s--) {\n'
'      var nk = (info.notes[s]+f) % 12;\n'
'      h += "<div class=\'sf s_"+s+"\'><span class=\'sfs\' id=\'sfs_"+s+"_"+f+"\'>"+Note.getNote(nk)+"</span></div>";\n'
'    }\n'
'    h += "</div>";\n'
'  }\n'
'  h += "</div></div>";\n'
'  return h;\n'
'}\n'
'\n'
'function generateTuningDropdown(info) {\n'
'  var ns = info.notes.length;\n'
'  var stdNotes = info.notes.slice().reverse().map(function(n){return Note.getNote(n);}).join("");\n'
'  var h = "<select name=\'tuning\' id=\'tuning\'><option value=\'\'>Standard ("+stdNotes+")</option><option value=\'custom\'>-- Custom --</option>";\n'
'  info.tuningAr.forEach(function(t){\n'
'    var n = t[1].slice().reverse().map(function(k){return Note.getNote(k);}).join("");\n'
'    h += "<option value=\'"+t[0]+"\'>"+t[2]+" ("+n+")</option>";\n'
'  });\n'
'  h += "</select><div class=\'customTuningCon hidden\'>";\n'
'  for (var s = ns; s >= 1; s--) {\n'
'    var cur = info.notes[s-1] % 12;\n'
'    h += "<div><select name=\'s"+s+"\' id=\'s"+s+"\' class=\'stringTuningSelect\'>";\n'
'    NOTE_VALUES.forEach(function(val,idx){\n'
'      h += "<option value=\'"+val+"\'"+(idx===cur?" selected":"")+">"+Note.getNote(idx)+"</option>";\n'
'    });\n'
'    h += "</select></div>";\n'
'  }\n'
'  h += "</div>";\n'
'  return h;\n'
'}\n'
'\n'
'function updateCapoOptions(info) {\n'
'  var sel = document.getElementById("capo_fret");\n'
'  if (!sel) return;\n'
'  var html = "<option value=\'0\'>None</option>";\n'
'  for (var f = 1; f <= (info.num_frets_tablet||10); f++)\n'
'    html += "<option value=\'"+f+"\'>Fret "+f+"</option>";\n'
'  sel.innerHTML = html;\n'
'}\n'
'\n'
'function switchInstrument(code) {\n'
'  var info = allInstrumentsData[code];\n'
'  window.instrumentInfo = info;\n'
'  var meta = instrumentMeta[code];\n'
'  document.getElementById("instrument_css").href = "assets/"+meta.css+".min.css";\n'
'  var isPiano = (code === "piano");\n'
'  $("#stringed_section").toggle(!isPiano);\n'
'  $("#piano_section").toggle(isPiano);\n'
'  $("#tuning_op").toggle(!isPiano);\n'
'  $("#stringed_extra_ops").toggle(!isPiano);\n'
'  if (!isPiano) {\n'
'    $("#stringed_section").html(generateFretboard(info));\n'
'    $("#tuning_con").html(generateTuningDropdown(info));\n'
'    updateCapoOptions(info);\n'
'  }\n'
'  PageMeta.pageType = "scales";\n'
'  ScalesPage.init();\n'
'  PageMeta.pageType = "scales";\n'
'}\n'
'\n'
'$(document).ready(function(){\n'
'  window.instrumentInfo = allInstrumentsData["guitar"];\n'
'  $("#stringed_section").html(generateFretboard(window.instrumentInfo));\n'
'  $("#tuning_con").html(generateTuningDropdown(window.instrumentInfo));\n'
'  updateCapoOptions(window.instrumentInfo);\n'
'  PageMeta.pageType = "scales";\n'
'  ScalesPage.init();\n'
'  PageMeta.pageType = "scales";\n'
'  $("#app_instrument_select").on("change", function(){ switchInstrument(this.value); });\n'
'});\n'
'</script>\n'
'</body>\n'
'</html>\n'
)

with open('D:/Reps/PETS/index.html', 'w', encoding='utf-8') as f:
    f.write(html)
print('Written index.html:', len(html), 'bytes')
